# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e856147b-2be8-4a79-99c9-bc0b43da4afd";
      fsType = "btrfs";
      options = [ "subvol=@rootnix" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/f2d00b06-8163-4fc6-8d7c-bd81cf90106f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/e856147b-2be8-4a79-99c9-bc0b43da4afd";
      fsType = "btrfs";
      options = [ "subvol=@boot" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e856147b-2be8-4a79-99c9-bc0b43da4afd";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  swapDevices = [ ];

}
