palette = "tokyonight"

[palettes.tokyonight]
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
red = "#f7768e"
yellow = "#e0af68"
bright_blue = "#2ac3de"
bright_cyan = "#b4f9f8"
bright_green = "#73daca"
bright_magenta = "#ff007c"
bright_red = "#ff7a93"
bright_yellow = "#ff9e64"
