#!/bin/bash

# For now, pylearn2 is on the PYTHONPATH the ugly way.
if [ -e $HOME/src/pylearn2 ] ; then
    export PYTHONPATH=$HOME/src/pylearn2:$PYTHONPATH
fi

# If I have the articles SVN repository checked out, set up build environment.
if [ -e $HOME/src/articles ] ; then
    export BIBINPUTS=.:$HOME/src/articles/bib:
    export BSTINPUTS=.:$HOME/src/articles/bst:
    export TEXINPUTS=.:$HOME/src/articles/sty:
fi

if [ `echo $HOSTNAME | cut -d '.' -f 2` == 'iro' ] ; then
    # LISA-specific .bashrc imports
    if [ -e /opt/lisa/os/.local.bashrc ] ; then
        source /opt/lisa/os/.local.bashrc
    elif [ -e /data/lisa/data/local_export/.local.bashrc ] ; then
        source /data/lisa/data/local_export/.local.bashrc
    fi

    # Up-to-date Firefox.
    FIREFOX_BIN=/opt/lisa/os/firefox-16.0.2.x86_64
    if [ -e $FIREFOX_BIN ] ; then
        add_to_front_of_path $FIREFOX_BIN
    fi
    # 
    if [ -n "$_CONDOR_SLOT" ]; then
        CODE_PREFIX=/data/lisa/exp/wardefar/.local
        export PYTHONPATH=$CODE_PREFIX/lib/python2.7/site-packages:$PYTHONPATH
        export PYTHONPATH=$CODE_PREFIX/lib64/python2.7/site-packages:$PYTHONPATH
    fi
fi


alias psqljm='psql -h gershwin.iro.umontreal.ca -U ${USER} -d ${USER}_db'
